"""
Serverbound packets (client -> server) for Minecraft 1.21.4

Packet IDs are organized by protocol state:
- HANDSHAKING: 0x00
- LOGIN: 0x00-0x03
- CONFIGURATION: 0x00-0x08
- PLAY: 0x00-0x3A

Reference: https://wiki.vg/Protocol
"""

# Handshaking state packets
HANDSHAKE = 0x00

# Login state packets
LOGIN_START = 0x00
LOGIN_ACKNOWLEDGED = 0x03

# Configuration state packets
CONFIG_CLIENT_INFORMATION = 0x00
CONFIG_COOKIE_RESPONSE = 0x01
CONFIG_KEEP_ALIVE = 0x04
CONFIG_PONG = 0x05
CONFIG_KNOWN_PACKS = 0x07
CONFIG_ACKNOWLEDGE_FINISH = 0x03

# Play state packets (most commonly used)
PLAY_TELEPORT_CONFIRM = 0x00
PLAY_CHAT_MESSAGE = 0x07
PLAY_CLIENT_COMMAND = 0x0D
PLAY_KEEP_ALIVE = 0x1A
PLAY_PLAYER_POSITION = 0x1D
PLAY_PLAYER_DIGGING = 0x24
PLAY_INTERACT = 0x10
PLAY_ARM_SWING = 0x35
PLAY_SET_CREATIVE_SLOT = 0x32
PLAY_CONTAINER_CLICK = 0x0F
PLAY_CLOSE_CONTAINER = 0x0E
PLAY_SET_HELD_ITEM = 0x2C

__all__ = [
    # Handshaking
    "HANDSHAKE",
    # Login
    "LOGIN_START",
    "LOGIN_ACKNOWLEDGED",
    # Configuration
    "CONFIG_CLIENT_INFORMATION",
    "CONFIG_COOKIE_RESPONSE",
    "CONFIG_KEEP_ALIVE",
    "CONFIG_PONG",
    "CONFIG_KNOWN_PACKS",
    "CONFIG_ACKNOWLEDGE_FINISH",
    # Play
    "PLAY_TELEPORT_CONFIRM",
    "PLAY_CHAT_MESSAGE",
    "PLAY_CLIENT_COMMAND",
    "PLAY_KEEP_ALIVE",
    "PLAY_PLAYER_POSITION",
    "PLAY_PLAYER_DIGGING",
    "PLAY_INTERACT",
    "PLAY_ARM_SWING",
    "PLAY_SET_CREATIVE_SLOT",
    "PLAY_CONTAINER_CLICK",
    "PLAY_CLOSE_CONTAINER",
    "PLAY_SET_HELD_ITEM",
]
