"""
Clientbound packets (server -> client) for Minecraft 1.21.4

Packet IDs are organized by protocol state:
- LOGIN: 0x00-0x03
- CONFIGURATION: 0x00-0x0E
- PLAY: 0x00-0x7A

Reference: https://wiki.vg/Protocol
"""

# Login state packets
LOGIN_DISCONNECT = 0x00
LOGIN_ENCRYPTION_REQUEST = 0x01
LOGIN_SUCCESS = 0x02
LOGIN_SET_COMPRESSION = 0x03

# Configuration state packets
CONFIG_COOKIE_REQUEST = 0x00
CONFIG_PLUGIN_MESSAGE = 0x01
CONFIG_DISCONNECT = 0x02
CONFIG_FINISH = 0x03
CONFIG_KEEP_ALIVE = 0x04
CONFIG_PING = 0x05
CONFIG_REGISTRY_DATA = 0x07
CONFIG_FEATURE_FLAGS = 0x0C
CONFIG_UPDATE_TAGS = 0x0D
CONFIG_KNOWN_PACKS = 0x0E

# Play state packets (most commonly used)
PLAY_DISCONNECT = 0x1A
PLAY_KEEP_ALIVE = 0x27
PLAY_JOIN_GAME = 0x2C
PLAY_PLAYER_POSITION = 0x42
PLAY_RESPAWN = 0x3D
PLAY_GAME_STATE_CHANGE = 0x4A
PLAY_UPDATE_TIME = 0x4E
PLAY_UPDATE_HEALTH = 0x52
PLAY_PLAYER_INFO_REMOVE = 0x3F
PLAY_PLAYER_INFO_UPDATE = 0x40
PLAY_SYSTEM_CHAT = 0x73
PLAY_LEVEL_CHUNK_WITH_LIGHT = 0x28
PLAY_BLOCK_UPDATE = 0x0A
PLAY_SET_SLOT = 0x14
PLAY_WINDOW_ITEMS = 0x11

__all__ = [
    # Login
    "LOGIN_DISCONNECT",
    "LOGIN_ENCRYPTION_REQUEST",
    "LOGIN_SUCCESS",
    "LOGIN_SET_COMPRESSION",
    # Configuration
    "CONFIG_COOKIE_REQUEST",
    "CONFIG_PLUGIN_MESSAGE",
    "CONFIG_DISCONNECT",
    "CONFIG_FINISH",
    "CONFIG_KEEP_ALIVE",
    "CONFIG_PING",
    "CONFIG_REGISTRY_DATA",
    "CONFIG_FEATURE_FLAGS",
    "CONFIG_UPDATE_TAGS",
    "CONFIG_KNOWN_PACKS",
    # Play
    "PLAY_DISCONNECT",
    "PLAY_KEEP_ALIVE",
    "PLAY_JOIN_GAME",
    "PLAY_PLAYER_POSITION",
    "PLAY_RESPAWN",
    "PLAY_GAME_STATE_CHANGE",
    "PLAY_UPDATE_TIME",
    "PLAY_UPDATE_HEALTH",
    "PLAY_PLAYER_INFO_REMOVE",
    "PLAY_PLAYER_INFO_UPDATE",
    "PLAY_SYSTEM_CHAT",
    "PLAY_LEVEL_CHUNK_WITH_LIGHT",
    "PLAY_BLOCK_UPDATE",
    "PLAY_SET_SLOT",
    "PLAY_WINDOW_ITEMS",
]
